=== yimiqidage/study-by-boot/src/main/java/com/test/xml/dom4j/services.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
		targetNamespace="http://up.sohu.com/peak/channel/services"
	elementFormDefault="qualified">
	<xs:annotation>
		<xs:appinfo>services.xsd</xs:appinfo>
		<xs:documentation>针对services.xml书写格式，进行约束，编写的xsd</xs:documentation>
	</xs:annotation>
	
	<xs:element name="services">
		<xs:complexType >
			<xs:sequence maxOccurs="unbounded"> <!-- xs:sequence 要求子元素必须按顺序出现。每个子元素可出现 0 到任意次数。 -->
				<xs:element name="service">
					<xs:complexType>
						<xs:all> <!-- xs:all 规定子元素能够以任意顺序出现，每个子元素可出现零次或一次。注意与  xs:sequence 区别。 -->
							<xs:element name="service-name" type="xs:string" minOccurs="1" maxOccurs="1"/><!-- 设置简单类型 -->
							<xs:element name="service-class" type="xs:string" minOccurs="1" maxOccurs="1"/>
							<xs:element name="service-type" minOccurs="1" maxOccurs="1">
								<xs:simpleType >  <!-- 设置 service-type ，只能为以下值-->
								  <xs:restriction base="xs:string">
								    <xs:enumeration value="xml"/>
								    <xs:enumeration value="text"/>
								    <xs:enumeration value="json"/>
								    <xs:enumeration value="form"/>
								    <xs:enumeration value="jump"/>
								    <xs:enumeration value="other"/>
								  </xs:restriction>
								</xs:simpleType>
							</xs:element>
							
							<xs:element name="service-params" minOccurs="0">
								<xs:complexType >
									<xs:sequence maxOccurs="unbounded">
										<xs:element name="param"> <!-- 设置仅含文本：http://www.w3school.com.cn/schema/schema_complex_text.asp -->
											<xs:complexType >
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute name="name" use="required" type="xs:string"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:all>
					</xs:complexType>
				</xs:element>	
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== yimiqidage/study-by-boot/src/main/java/com/test/xml/dom4j/alipay.xml
<?xml version="1.0" encoding="UTF-8"?>


<services xmlns="http://up.sohu.com/peak/channel/services"
		  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		  xsi:schemaLocation="http://up.sohu.com/peak/channel/services services.xsd"
>
	<service>
		<service-name>alipay</service-name>
		<service-class>com.sohu.rdapp.peak_channel.paygate.services.request.AlipayRequestService</service-class>
		<service-type>form</service-type>
		<service-params>
			<param name="service">create_direct_pay_by_user</param>
			<param name="partner">2088001884883961</param>
			<param name="_input_charset">GBK</param>
			<param name="sign_type">MD5</param>
			<param name="notify_url">/channel/gw/dyna/payres/alipay_notify</param>
			<param name="return_url">/channel/gw/dyna/payres/alipay_return</param>
			<param name="payment_type">1</param>
			<param name="seller_email">peakreg@vip.sohu.com</param>
			<param name="key">4uz8a6gmm1i9wc16bntan4k8uhhf8nuj</param>
			<param name="gateway">https://mapi.alipay.com/gateway.do</param>
			
		</service-params>
	</service>
	
	<service>
		<service-name></service-name>
		<service-type>form</service-type>
		<service-class></service-class>
		
	</service>
</services>
